services:
  - type: web
    name: prueba-tecnica-back
    runtime: node
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 23.6.1
